// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwzhdqetjprdnkdwlhzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3emhkcWV0anByZG5rZHdsaHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTM5MzIsImV4cCI6MjA2NTM2OTkzMn0.5rCtxqO9fWQACLn6jf8E4E9cqxHHB0OlXS4tqpcSjtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);